# Generated by Django 3.1.1 on 2020-09-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoholicIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('proof', models.IntegerField()),
                ('type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='NAIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('instructions', models.TextField()),
                ('ingredientAmount', models.TextField()),
                ('NAIngredients', models.ManyToManyField(to='bartender.NAIngredient')),
                ('liquor', models.ManyToManyField(to='bartender.AlcoholicIngredient')),
            ],
        ),
    ]
