# Generated by Django 3.1.1 on 2020-09-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bartender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alcoholicingredient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='alcoholicingredient',
            name='proof',
        ),
    ]
