# Generated by Django 3.1.1 on 2020-09-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bartender', '0002_auto_20200907_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alcoholicingredient',
            old_name='type',
            new_name='name',
        ),
    ]
