# Generated by Django 3.1.1 on 2020-09-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartender', '0005_auto_20200907_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoholicingredient',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='naingredient',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
